### PR TITLE
Added Server 2016 + escape invalid data

### PR DESCRIPTION
**Pull request by covidium**
Added Windows 2016 support and escaped invalid data for JSON.parse

### CODE REVIEW

**Comment by covidium** [comment]
@dylanratcliffe are you still maintaining this project?

**Comment by dylanratcliffe** [comment]
Yep, notifications had been off though. Will test and merge

**Comment by natemccurdy** [comment]
@covidium This doesn't seem to work for me on Windows 2016. All of the facts are showing up as empty hashes or arrays, and the command is still trying to be run with `999`.

screen shot 2017-05-10 at 10 37 12 am

**Comment by covidium** [comment]
@natemccurdy Sorry about that.
Fixed and now should work as expected also in Windows 2016.

**Comment by dylanratcliffe** [comment]
@covidium Thanks for the work on this. I've used your code to re-implement with a little more open logic (which will likely need to be changed again but we will see) Release 0.1.3

**Pull request closed without merging**
